### ISSUE TITLE
Spell casting action activates when changing character inventory in any way

### ISSUE THREAD

**Issue by BardurArantsson** [r-e-d/LeUI-SoD#1]
Hi,

This is a bit of weird one: I have this issue where changing a character's equipped items in any way (and also putting items in bags) automatically activates the spellcasting menu when I exit the inventory screen. The character I'm running right now is a F/M Half-elf if that matters. AI is turned off.

It's not a **huge** deal since i'm running solo I can just press 2 and then 1 to deactivate the menu, but it's a bit of an annoyance :smile: 

I've observed this on both 2.5.x (w/4.3.2) and 2.6.x (w/4.5), but on 2.5.x it appears to only happen when dropping items into bags.

Your mod is the only UI mod I'm running (well, also the auto-roller).

**Comment by BardurArantsson** [comment]
Addendum: In fact it also happens even just moving items around in the character's backpack.

**Comment by BardurArantsson** [comment]
Oh, forgot to mention: The spellcasting menu shown at the bottom includes *all* the spells known to the character even if they aren't memorized.

**Comment by r-e-d** [comment]
Do you have other mods installed? I can't reproduce with only this mod.

**Comment by BardurArantsson** [comment]
Oh, yes, sorry should have specified the full list. I've attached my weidu.log.

[weidu.log](https://github.com/r-e-d/LeUI-SoD/files/9745128/weidu.log)

**Comment by BardurArantsson** [comment]
Hum, it seems this doesn't happen consistently. Just booted up the game again and now everything works as expected.

It seems it may require playing for a long time or something? This is confusing me because yesterday I definitely tried to restart the game before reporting. :shrug: 

I wonder if it's somehow related to some saved state or something. I'll close for now now and just keep adding observations as I make them.

**Comment by BardurArantsson** [comment]
... and *just* as I say that I find a way to reproduce with one of my save games. If I load that game and press F1 (talk) and then F2 the spell-casting menu appears (again w/all spells shown even non-memorized ones).

It doesn't happen with a completely fresh character, though :(
